modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="mysty_gunmod"
version="1.0"
displayName="Gun Mod"
logoFile="gunmod.png"
authors="Mystical Mike"
description='''
Adds guns
'''

[[dependencies.mysty_gunmod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mysty_gunmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
